name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code.
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python (if needed for tests or scripts).
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install dependencies.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build the Docker image.
      - name: Build Docker Image
        run: docker build -t ai-jackpot-generator .

      # 5. Configure AWS Credentials for subsequent AWS CLI commands.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. Log in to Amazon ECR using v2. Note that registryIds should be just the 12-digit AWS account ID.
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registryIds: ${{ secrets.AWS_ACCOUNT_ID }}
          mask-password: "false"

      # 7. Tag the Docker image using the registry output from the login step.
      - name: Tag Docker Image
        run: |
          docker tag ai-jackpot-generator:latest ${{ steps.login-ecr.outputs.registry }}/apps/jackpotteller:latest

      # 8. Push the Docker image to ECR.
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/apps/jackpotteller:latest

      # 9. Set up kubectl.
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.0"

      # 10. Update kubeconfig for EKS cluster.
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ai-jackpot-cluster

      # 11. Deploy Kubernetes manifests.
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/cronjob.yaml
          kubectl apply -f k8s/ingress.yaml
